### PR TITLE
[d3d8] Validate depth stencil formats

### LINKED ISSUE #87: Nosferatu - Wrath Of Malachi crashes on startup
The game outright crashes with the following error message:

Error

It works fine with WineD3D, but during gameplay it drops to an astounding 3 fps... unless the game is doing some form of ray tracing in d3d8 (supposedly it's built using a "Architectural Generator Engine"), I'm not sure what's going on. It's unplayable in its current state, so maybe something d8vk can help "resurrect".

The attached trace plays back fine and doesn't reproduce the crash, sadly.

### Software information
Nosferatu - Wrath Of Malachi (GOG)

### System information
- GPU: Intel Xe (TigerLake GT2)
- Driver: ANV/Mesa 23.0.99
- Wine version: 7.22 Staging
- DXVK version: d0f5903

### Apitrace file(s)
[Nosferatu.trace.tar.xz](https://drive.google.com/file/d/1bE08qVQ-wplvCicMEZeTmd69zpCQPK2_/view?usp=share_link)

### Log files
- d3d8.log: [Nosferatu_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/10429154/Nosferatu_d3d8.log)
- d3d9.log: [Nosferatu_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/10429156/Nosferatu_d3d9.log)

### LINKED ISSUE #88: Iron Storm crashes on startup
Crashes on startup with d8vk, works fine with WineD3D. Attached trace doesn't reproduce the crash. Based on the logs I suspect the game (or d8vk) for some reason attempts to set an unsupported resolution (800x450) and crashes, perhaps?

Based on its own config files, the game supposedly should use:
```
		:Resolution
		{
			Device 0
			x 640
			y 480
			bpp 16
			fullscreen 1
		}
```

### Software information
Iron Storm (GOG)

### System information
- GPU: Intel Xe (TigerLake GT2)
- Driver: ANV/Mesa 23.0.99
- Wine version: 7.22 Staging
- DXVK version: d0f5903

### Apitrace file(s)
[IronStorm.trace.tar.xz](https://drive.google.com/file/d/1VcrnreMQ27511r0Og9QX30Bu9Izeq9rz/view?usp=share_link)

### Log files
- d3d8.log: [IronStorm_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/10429296/IronStorm_d3d8.log)
- d3d9.log: [IronStorm_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/10429297/IronStorm_d3d9.log)

### LINKED ISSUE #118: D3D8 depth stencil format shenanigans
I wrote a series of tests in [d8vk-tests](https://github.com/WinterSnowfall/d8vk-tests) following my discoveries on #87 and #88. 

The tests comprise of first querying all the DS formats via CheckDepthStencilMatch() and then attempting to CreateDevice() if the first call returns D3D_OK. If CheckDepthStencilMatch() returns D3DERR_NOTAVAILABLE I consider the format is unsupported and do not attempt creating a device.

This is the output with WineD3D:
image

And this is the output with d8vk:
image

These appear to fail when forwarded to d3d9 code, and I'm not sure what's going on or why WineD3D outright reports them as not available.

Should d8vk disable them as well?

### PR DESCRIPTION
**Pull request by WinterSnowfall**
Fixes #87 , fixes #88  and fixes #118 (addressing the points highlighted therein). I'm not entirely sure if it breaks something or if we should rather app profile these formats rather than outright not supporting them, however this approach seems to be in line with both what native d3d8 and WineD3D are currently doing. Also not entirely sure if this is in any way relevant to d3d9, which is why I've kept everything in d3d8 code.

### CODE REVIEW

File: src/d3d8/d3d8_format.h [hunk 1]
```diff
@@ -15,6 +15,17 @@ namespace dxvk {
     return isDXT(D3DFORMAT(fmt));
   }
 
+  inline constexpr bool isSupportedDepthStencilFormat(D3DFORMAT fmt) {
+    // native d3d8 doesn't support D3DFMT_D32, D3DFMT_D15S1 or D3DFMT_D24X4S4
```
Comment (AlpyneDreams) [inline src/d3d8/d3d8_format.h:19]: How do we know this? Is this just modern versions of d3d8 or did it always never support these? Does that also apply for all hardware?

File: src/d3d8/d3d8_format.h [hunk 2]
```diff
@@ -38,7 +49,7 @@ namespace dxvk {
       case D3DFMT_V8U8:
       case D3DFMT_L6V5U5:
       case D3DFMT_D16_LOCKABLE:
-      case D3DFMT_D15S1:
+      //case D3DFMT_D15S1:
```
Comment (AlpyneDreams) [inline src/d3d8/d3d8_format.h]: We should still return the correct stride for unsupported formats.

**Review by AlpyneDreams — CHANGES_REQUESTED** [review]
Very helpful PR, thanks a ton! Just a couple things...

Why does this fix those issues? Was there something in d9vk that stopped those formats from working or were applications just picking formats they didn't know how to use?

File: src/d3d8/d3d8_format.h (hunk 1 above)
Comment (WinterSnowfall) [reply src/d3d8/d3d8_format.h:19]: We've checked on native Nvidia and Intel and I've also written some test for these bits (see [d8vk-tests](https://github.com/WinterSnowfall/d8vk-tests)). Both Nvidia/Intel report these formats as unsupported on Windows (@Blisto91 checked on AMD, it's the same) and WineD3D also does the same. This is why the games worked with WineD3D. As to what is happening behind the scenes (basically what is crashing) I am unsure. The games will crash if allowed to pick these formats, that much is certain.

File: src/d3d8/d3d8_format.h (hunk 2 above)
Comment (WinterSnowfall) [reply src/d3d8/d3d8_format.h]: Alright, will leave these as they were.

**Comment by AlpyneDreams** [comment]
I think this is probably the right move. Let's wait until we figure out #118 for sure.

**Comment by WinterSnowfall** [comment]
Just to clarify, because my :potato: memory remembered some things in the meantime, creating a device with any of these 3 formats will fail. That's what is causing the games to crash (d8vk or d9vk do not crash, they just report the device creation failed back to the apps, which then panic and crash, since **CheckDepthStencilMatch** had given them the all clear for said formats). I'm assuming based on the results of the tests I've mentioned in #118 that these formats weren't all that supported by drivers anyway, if ever.

**Review by AlpyneDreams — APPROVED** [review]
