### PR TITLE
[d3d8] Ensure all references are cleared before d3d9 device reset

### LINKED ISSUE #174: Deer Hunter 2004 resolution change freeze
In Deer Hunter 2004 the rendering will freeze when you attempt to change the resolution in the video settings. This does not happen with wined3d

<details>
  <summary>Screenshot</summary>

Screenshot_20230710_215002
</details>

### Software information
Deer Hunter 2004 (Deer Hunger GOLD EDITION)

### System information
- GPU: 7900xtx
- Driver: mesa-git
- Wine version: Proton as the game crashes when entering video settings with regular Wine
- DXVK version: Latest main from artifacts

### Apitrace file(s)
https://drive.proton.me/urls/KJ0VXXBBVG#LjSTWdsn05Mb
One with wined3d where it works and one with d8vk where it gets stuck

### Log files
[DH2004_d3d9.log](https://github.com/AlpyneDreams/d8vk/files/12006130/DH2004_d3d9.log)
[Game.LOG](https://github.com/AlpyneDreams/d8vk/files/12006131/Game.LOG)

### LINKED ISSUE #175: Castle Strike break when alt tabbing
Alt tabbing in Castle Strike will make you not able to go ingame again. This is likely due to some upstream work from a rebase.

### Software information
Castle Strike

### System information
- GPU: 7900xtx
- Driver: mesa-git
- Wine version: 8.12
- DXVK version: Master and https://github.com/AlpyneDreams/d8vk/pull/172 
Remaining resources is lower with the latter 
### Apitrace file(s)
[Castlestrike.tar.gz](https://github.com/AlpyneDreams/d8vk/files/12008913/Castlestrike.tar.gz)
One with d8vk and one with wined3d

### Log files
[Castlestrike_d3d8.log](https://github.com/AlpyneDreams/d8vk/files/12008849/Castlestrike_d3d8.log)
[Castlestrike_d3d9.tar.gz](https://github.com/AlpyneDreams/d8vk/files/12008850/Castlestrike_d3d9.tar.gz)

### PR DESCRIPTION
**Pull request by WinterSnowfall**
Now that we've imported the new D3D9 device reset validations we also need ensure that:

- We clear all d3d8 cached references before calling d3d9 device reset

- We regenerate/rebind the backbuffers and autoDS after the d3d9 device reset succeeds

- We actually free state blocks on calls to DeleteStateBlock() 

Otherwise some d3d8 games will livelock and crash, complaining they can't reset the device with bound resources (it was the default render target, depth stencil and state blocks that were bound from our end). 

Fixes #174, fixes #175, partially addresses #59 (fixes the startup crash, as that seems to have been state block related).

### CODE REVIEW

File: src/d3d8/d3d8_device.cpp [hunk 1]
```diff
@@ -214,14 +212,16 @@ namespace dxvk {
...
+
     d3d9::D3DPRESENT_PARAMETERS params = ConvertPresentParameters9(pPresentationParameters);
     HRESULT res = GetD3D9()->Reset(&params);
 
     if (FAILED(res))
       return res;
 
-    m_presentParams = *pPresentationParameters;
-    ResetState();
+    RegenBackBuffersAndAutoDepthStencil();
```
Comment (K0bin) [inline src/d3d8/d3d8_device.cpp]: Recreate sounds nicer. :)

File: src/d3d8/d3d8_device.cpp [hunk 2]
```diff
@@ -970,6 +970,7 @@ namespace dxvk {
 
     D3D8StateBlock* block = reinterpret_cast<D3D8StateBlock*>(Token);
     m_stateBlocks.erase(block);
+    delete block;
```
Comment (K0bin) [inline src/d3d8/d3d8_device.cpp:974]: Wouldn't it be more elegant to turn m_stateBlocks into a vector of unique_ptrs?

Comment (WinterSnowfall) [reply src/d3d8/d3d8_device.cpp:974]: How would that help things? The current solution of using the block address as a token is a bit janky anyway, I'll say that much... (but sort of guarantees they'll be unique). P.S.: Not entirely sure why Alpyne went with a set in the first place, but maybe the token logic will be changed at some point. It's not in the scope of this PR to change how that works really.

File: src/d3d8/d3d8_device.cpp (hunk 1 above)
Comment (WinterSnowfall) [reply src/d3d8/d3d8_device.cpp]: I'm very uninspired when it comes to naming...

**Comment by WinterSnowfall** [comment]
There still seem to be some issues around bound resources (e.g. with Scrapland Remastered at times), but I don't think there's anything left to fix on d8vk end. Remaining discrepancies may just be games doing stupid things or differences in handling between d3d8 and d3d9 (let's hope not...).

Either way, this PR fixes most of the issues, but caveat emptor the saga may not be entirely over.

**Comment by WinterSnowfall** [comment]
As I long feared, there's a difference between how d3d8 and d3d9 handle losable resource validation on device resets, in that d3d9 counts state blocks as losable resources while d3d8 does not. This appears to be a rare case where the docs are actually on point:
 
Here's d3d8:
>Before calling the Reset method for a device, an application should release any explicit render targets, depth stencil surfaces, additional swap chains and D3DPOOL_DEFAULT resources associated with the device.

And d3d9:
>Before calling the IDirect3DDevice9::Reset method for a device, an application should release any explicit render targets, depth stencil surfaces, additional swap chains, state blocks, and D3DPOOL_DEFAULT resources associated with the device.

We'll have to disable losable counts for state blocks in d9vk via the bridge when using it with d8vk. I'll PR something separately against dxvk to address this.

Edit: https://github.com/doitsujin/dxvk/pull/3665
Need to add a one-liner in the bridge constructor after this is merged and we rebase, after which is should be fine (hopefully for good).

**Comment by WinterSnowfall** [comment]
Since there may be some time still until we rebase and all of this is merged, note to self that with the latest upstream code we still need to plop a call to SetD3D8CompatibilityMode as follows:

    // Get the bridge interface to D3D9.
    if (FAILED(GetD3D9()->QueryInterface(__uuidof(IDxvkD3D8Bridge), (void**)&m_bridge))) {
      throw DxvkError("D3D8Device: ERROR! Failed to get D3D9 Bridge. d3d9.dll might not be DXVK!");
    }

    m_bridge->SetAPIName("D3D8");
    m_bridge->SetD3D8CompatibilityMode(true);

for everything to work properly.

**Comment by WinterSnowfall** [comment]
And there I was, dear reader, chasing refs again...

D3DPOOL_DEFAULT resources are a problem now, since anything lingering on a device reset will cause games to crash. I managed to narrow down such an obscure case, by following it up to the temporary blit surfaces we were (in some cases) creating during CopyRects. 

The problem there was mainly with that extra refcount that was keeping the blit surfaces around even after surface (containing object) destruction - since we're passing everything around as a public COM, the refcount for `m_blitImage` will stay a very constant 1 (as sent to us by d3d9). COM1 = COM2 will always keep COM2's refcount constant (increase on assignment to COM1, decrease on release of COM1), so that makes sense.

With the extra ref it was, unfortunately, always stuck at a very constant 2 and never destroyed. An easy enough fix, but it took me quite some time to figure it out.

~Also took the liberty to use CreateOffscreenPlainSurface instead of CreateRenderTarget, because:~
~- It's now very obvious we're creating the surface in D3DPOOL_DEFAULT~
~- Less useless parameters passed around~
~- The naming better suits our end purpose, since we don't actually need a RT~

Nevemind on the last bit, turns out using RTs is somewhat faster (probably because they're not lockable). I've added a note so that we don't forget we need to be extra careful when messing about with object lifecycle in this area.

File: src/d3d8/d3d8_device.cpp (hunk 2 above)
Comment (WinterSnowfall) [reply src/d3d8/d3d8_device.cpp:974]: @K0bin I will PR something that reworks this bit post-upstreaming. In short, native d3d8 uses incremental token values to identify state blocks, not their addresses, so m_stateBlocks needs to turn into an unordered_map of DWORD and D3D8StateBlock*. The token DWORD will start at 0 and monotonically increase throughout the lifecycle of a device, whenever a new state block is created.

**Comment by WinterSnowfall** [comment]
I've included the bridge call to enable the D3D8 compatibility mode (which currently only affects state block tracking for device reset). Note however this will cause issues until a rebase is performed, since the necessary bridge code was added directly upstream.
